version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/app/:cached
      - static:/srv:delegated
    depends_on:
      - db
    ports:
      - '8000:8000'

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  static:
  db-data:
