# Generated by Django 4.2.7 on 2023-11-28 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cell_weights",
                    models.JSONField(
                        default={
                            1: 20,
                            2: 100,
                            3: 45,
                            4: 70,
                            5: 15,
                            6: 140,
                            7: 20,
                            8: 20,
                            9: 140,
                            10: 45,
                        }
                    ),
                ),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "cells_remaining",
                    models.JSONField(default="[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameRoundLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "given_number",
                    models.PositiveSmallIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.gameround",
                    ),
                ),
            ],
        ),
    ]
